import { MEDIA_AUDIO_FIELD_LABELS } from "./media-audio-field-metadata.js";

export const FIELD_LABELS: Record<string, string> = {
  meta: "元数据",
  "meta.lastTouchedVersion": "配置最近修改版本",
  "meta.lastTouchedAt": "配置最近修改时间",
  env: "环境",
  "env.shellEnv": "Shell 环境导入",
  "env.shellEnv.enabled": "启用 Shell 环境导入",
  "env.shellEnv.timeoutMs": "Shell 环境导入超时（毫秒）",
  "env.vars": "环境变量覆盖",
  wizard: "设置向导状态",
  "wizard.lastRunAt": "向导上次运行时间",
  "wizard.lastRunVersion": "向导上次运行版本",
  "wizard.lastRunCommit": "向导上次运行提交",
  "wizard.lastRunCommand": "向导上次运行命令",
  "wizard.lastRunMode": "向导上次运行模式",
  diagnostics: "诊断",
  "diagnostics.otel": "OpenTelemetry",
  "diagnostics.cacheTrace": "缓存追踪",
  logging: "日志",
  "logging.level": "日志级别",
  "logging.file": "日志文件路径",
  "logging.consoleLevel": "控制台日志级别",
  "logging.consoleStyle": "控制台日志样式",
  "logging.redactSensitive": "敏感数据脱敏模式",
  "logging.redactPatterns": "自定义脱敏模式",
  cli: "CLI",
  "cli.banner": "CLI 横幅",
  "cli.banner.taglineMode": "CLI 横幅标语模式",
  update: "更新",
  "update.channel": "更新通道",
  "update.checkOnStart": "启动时检查更新",
  "update.auto.enabled": "启用自动更新",
  "update.auto.stableDelayHours": "自动更新稳定延迟（小时）",
  "update.auto.stableJitterHours": "自动更新稳定抖动（小时）",
  "update.auto.betaCheckIntervalHours": "自动更新 Beta 检查间隔（小时）",
  "diagnostics.enabled": "启用诊断",
  "diagnostics.flags": "诊断标志",
  "diagnostics.stuckSessionWarnMs": "卡住会话警告阈值（ms）",
  "diagnostics.otel.enabled": "启用 OpenTelemetry",
  "diagnostics.otel.endpoint": "OpenTelemetry 端点",
  "diagnostics.otel.protocol": "OpenTelemetry 协议",
  "diagnostics.otel.headers": "OpenTelemetry 请求头",
  "diagnostics.otel.serviceName": "OpenTelemetry 服务名",
  "diagnostics.otel.traces": "启用 OpenTelemetry 追踪",
  "diagnostics.otel.metrics": "启用 OpenTelemetry 指标",
  "diagnostics.otel.logs": "启用 OpenTelemetry 日志",
  "diagnostics.otel.sampleRate": "OpenTelemetry 采样率",
  "diagnostics.otel.flushIntervalMs": "OpenTelemetry 刷新间隔（ms）",
  "diagnostics.cacheTrace.enabled": "启用缓存追踪",
  "diagnostics.cacheTrace.filePath": "缓存追踪文件路径",
  "diagnostics.cacheTrace.includeMessages": "缓存追踪包含消息",
  "diagnostics.cacheTrace.includePrompt": "缓存追踪包含提示词",
  "diagnostics.cacheTrace.includeSystem": "缓存追踪包含系统",
  "agents.list.*.identity.avatar": "身份头像",
  "agents.list.*.skills": "代理技能过滤器",
  "agents.list[].runtime": "代理运行时",
  "agents.list[].runtime.type": "代理运行时类型",
  "agents.list[].runtime.acp": "代理 ACP 运行时",
  "agents.list[].runtime.acp.agent": "代理 ACP 宿主代理",
  "agents.list[].runtime.acp.backend": "代理 ACP 后端",
  "agents.list[].runtime.acp.mode": "代理 ACP 模式",
  "agents.list[].runtime.acp.cwd": "代理 ACP 工作目录",
  "agents.list[].thinkingDefault": "默认思考模式",
  "agents.list[].reasoningDefault": "默认推理模式",
  "agents.list[].fastModeDefault": "默认快速模式",
  agents: "代理",
  "agents.defaults": "代理默认值",
  "agents.list": "代理列表",
  gateway: "网关",
  "gateway.port": "网关端口",
  "gateway.mode": "网关模式",
  "gateway.bind": "网关绑定模式",
  "gateway.customBindHost": "网关自定义绑定主机",
  "gateway.controlUi": "控制界面",
  "gateway.controlUi.enabled": "启用控制界面",
  "gateway.auth": "网关认证",
  "gateway.auth.mode": "网关认证模式",
  "gateway.auth.allowTailscale": "网关 认证 允许 Tailscale 身份",
  "gateway.auth.rateLimit": "网关 认证 速率限制",
  "gateway.auth.trustedProxy": "网关可信代理认证",
  "gateway.trustedProxies": "网关 可信代理 CIDR 列表",
  "gateway.allowRealIpFallback": "网关 允许 x-real-ip 回退",
  "gateway.tools": "网关 工具 暴露 策略",
  "gateway.tools.allow": "网关 工具 允许列表",
  "gateway.tools.deny": "网关 工具 拒绝列表",
  "gateway.channelHealthCheckMinutes": "网关 通道 健康检查 间隔（min）",
  "gateway.channelStaleEventThresholdMinutes": "网关 通道 陈旧事件 阈值（min）",
  "gateway.channelMaxRestartsPerHour": "网关 通道 最大 每 小时",
  "gateway.tailscale": "网关 Tailscale",
  "gateway.tailscale.mode": "网关 Tailscale 模式",
  "gateway.tailscale.resetOnExit": "网关 Tailscale 退出时重置 退出",
  "gateway.remote": "远程网关",
  "gateway.remote.transport": "远程网关 传输",
  "gateway.reload": "配置重载",
  "gateway.tls": "网关 TLS",
  "gateway.tls.enabled": "启用网关 TLS",
  "gateway.tls.autoGenerate": "网关 TLS 自动生成证书",
  "gateway.tls.certPath": "网关 TLS 证书 路径",
  "gateway.tls.keyPath": "网关 TLS 键 路径",
  "gateway.tls.caPath": "网关 TLS CA 路径",
  "gateway.http": "网关 HTTP API",
  "gateway.http.endpoints": "网关 HTTP 端点",
  "gateway.http.securityHeaders": "网关 HTTP 安全 请求头",
  "gateway.http.securityHeaders.strictTransportSecurity": "严格传输安全 请求头",
  "gateway.remote.url": "远程网关 URL",
  "gateway.remote.sshTarget": "远程网关 SSH 目标",
  "gateway.remote.sshIdentity": "远程网关 SSH 身份",
  "gateway.remote.token": "远程网关 令牌",
  "gateway.remote.password": "远程网关 密码",
  "gateway.remote.tlsFingerprint": "远程网关 TLS 指纹",
  "gateway.auth.token": "网关令牌",
  "gateway.auth.password": "网关密码",
  browser: "浏览器",
  "browser.enabled": "启用浏览器",
  "browser.cdpUrl": "浏览器 CDP URL",
  "browser.color": "浏览器 强调色",
  "browser.executablePath": "浏览器 可执行文件 路径",
  "browser.headless": "浏览器 无头 模式",
  "browser.noSandbox": "浏览器 无沙箱 模式",
  "browser.attachOnly": "浏览器 仅附加 模式",
  "browser.cdpPortRangeStart": "浏览器 CDP 端口范围起始值",
  "browser.defaultProfile": "浏览器 默认 配置",
  "browser.profiles": "浏览器 配置集",
  "browser.profiles.*.cdpPort": "浏览器 配置 CDP 端口",
  "browser.profiles.*.cdpUrl": "浏览器 配置 CDP URL",
  "browser.profiles.*.userDataDir": "浏览器 配置 用户数据 目录",
  "browser.profiles.*.driver": "浏览器 配置 驱动",
  "browser.profiles.*.attachOnly": "浏览器 配置 仅附加 模式",
  "browser.profiles.*.color": "浏览器 配置 强调色",
  tools: "工具",
  "tools.allow": "工具允许列表",
  "tools.deny": "工具拒绝列表",
  "tools.web": "Web 工具",
  "tools.exec": "Exec 工具",
  "tools.media.image.enabled": "启用图像理解",
  "tools.media.image.maxBytes": "图像理解最大字节",
  "tools.media.image.maxChars": "图像理解最大字符",
  "tools.media.image.prompt": "图像理解提示词",
  "tools.media.image.timeoutSeconds": "图像理解超时（sec）",
  "tools.media.image.attachments": "图像理解附加策略",
  "tools.media.image.models": "图像理解模型",
  "tools.media.image.scope": "图像理解范围",
  "tools.media.models": "媒体理解共享模型",
  "tools.media.concurrency": "Media Understanding 并发",
  "tools.media.asyncCompletion.directSend": "异步 Media 完成直接发送",
  ...MEDIA_AUDIO_FIELD_LABELS,
  "tools.media.video.enabled": "启用视频理解",
  "tools.media.video.maxBytes": "视频理解最大字节",
  "tools.media.video.maxChars": "视频理解最大字符",
  "tools.media.video.prompt": "视频理解提示词",
  "tools.media.video.timeoutSeconds": "视频理解超时（sec）",
  "tools.media.video.attachments": "视频理解附加策略",
  "tools.media.video.models": "视频理解模型",
  "tools.media.video.scope": "视频理解范围",
  "tools.links.enabled": "启用链接理解",
  "tools.links.maxLinks": "链接理解最大链接数",
  "tools.links.timeoutSeconds": "链接理解超时（sec）",
  "tools.links.models": "链接理解模型",
  "tools.links.scope": "链接理解范围",
  "tools.profile": "工具配置",
  "tools.alsoAllow": "工具允许列表附加项",
  "agents.list[].tools.profile": "代理工具配置",
  "agents.list[].tools.alsoAllow": "代理工具允许列表附加项",
  "tools.byProvider": "工具策略 by 提供商",
  "agents.list[].tools.byProvider": "代理工具策略 by 提供商",
  "tools.exec.applyPatch.enabled": "启用 apply_patch",
  "tools.exec.applyPatch.workspaceOnly": "apply_patch 工作区-Only",
  "tools.exec.applyPatch.allowModels": "apply_patch 模型允许列表",
  "tools.loopDetection.enabled": "工具循环检测",
  "tools.loopDetection.historySize": "工具循环历史大小",
  "tools.loopDetection.warningThreshold": "工具循环警告阈值",
  "tools.loopDetection.criticalThreshold": "工具循环严重阈值",
  "tools.loopDetection.globalCircuitBreakerThreshold": "工具循环全局断路器阈值",
  "tools.loopDetection.detectors.genericRepeat": "工具循环通用重复检测",
  "tools.loopDetection.detectors.knownPollNoProgress": "工具循环轮询无进展检测",
  "tools.loopDetection.detectors.pingPong": "工具循环乒乓检测",
  "tools.fs.workspaceOnly": "工作区-only FS tools",
  "tools.sessions.visibility": "会话工具可见性",
  "tools.exec.notifyOnExit": "Exec 通知 On 退出",
  "tools.exec.notifyOnExitEmptySuccess": "Exec 通知 On Empty Success",
  "tools.exec.approvalRunningNoticeMs": "Exec Approval Running Notice（ms）",
  "tools.exec.host": "Exec 目标",
  "tools.exec.security": "Exec 安全",
  "tools.exec.ask": "Exec Ask",
  "tools.exec.node": "Exec Node 绑定",
  "tools.agentToAgent": "代理到代理 工具 访问",
  "tools.agentToAgent.enabled": "启用 代理到代理 工具",
  "tools.agentToAgent.allow": "代理到代理 目标 允许列表",
  "tools.experimental": "实验性 工具",
  "tools.experimental.planTool": "启用 Structured Plan 工具",
  "tools.elevated": "提权 工具 访问",
  "tools.elevated.enabled": "启用 提权 工具 访问",
  "tools.elevated.allowFrom": "提权 工具 允许 规则",
  "tools.subagents": "Subagent 工具 策略",
  "tools.subagents.tools": "Subagent 工具 允许/拒绝 策略",
  "tools.sandbox": "沙箱 工具 策略",
  "tools.sandbox.tools": "沙箱 工具 允许/拒绝 策略",
  "tools.exec.pathPrepend": "Exec PATH 前置",
  "tools.exec.safeBins": "Exec 安全可执行文件",
  "tools.exec.strictInlineEval": "Require 内联求值 Approval",
  "tools.exec.safeBinTrustedDirs": "Exec 安全可执行文件 可信 目录s",
  "tools.exec.safeBinProfiles": "Exec 安全可执行文件 配置集",
  approvals: "审批",
  "approvals.exec": "Exec Approval 转发",
  "approvals.exec.enabled": "Forward Exec Approvals",
  "approvals.exec.mode": "Approval 转发 模式",
  "approvals.exec.agentFilter": "审批代理过滤器",
  "approvals.exec.sessionFilter": "审批会话过滤器",
  "approvals.exec.targets": "Approval 转发 目标s",
  "approvals.exec.targets[].channel": "Approval 目标 通道",
  "approvals.exec.targets[].to": "Approval 目标 目标地址",
  "approvals.exec.targets[].accountId": "Approval 目标 账户 ID",
  "approvals.exec.targets[].threadId": "Approval 目标 线程 ID",
  "approvals.plugin": "插件 Approval 转发",
  "approvals.plugin.enabled": "Forward 插件 Approvals",
  "approvals.plugin.mode": "插件 Approval 转发 模式",
  "approvals.plugin.agentFilter": "插件审批代理过滤器",
  "approvals.plugin.sessionFilter": "插件审批会话过滤器",
  "approvals.plugin.targets": "插件 Approval 转发 目标s",
  "approvals.plugin.targets[].channel": "插件 Approval 目标 通道",
  "approvals.plugin.targets[].to": "插件 Approval 目标 目标地址",
  "approvals.plugin.targets[].accountId": "插件 Approval 目标 账户 ID",
  "approvals.plugin.targets[].threadId": "插件 Approval 目标 线程 ID",
  "tools.message.allowCrossContextSend": "允许 跨上下文 Messaging",
  "tools.message.crossContext.allowWithinProvider": "允许 跨上下文（相同 提供商）",
  "tools.message.crossContext.allowAcrossProviders": "允许 跨上下文（跨 提供商）",
  "tools.message.crossContext.marker.enabled": "跨上下文 标记",
  "tools.message.crossContext.marker.prefix": "跨上下文 标记 前缀",
  "tools.message.crossContext.marker.suffix": "跨上下文 标记 后缀",
  "tools.message.broadcast.enabled": "启用 消息广播",
  "tools.web.search.enabled": "启用 Web 搜索 工具",
  "tools.web.search.provider": "Web 搜索提供商",
  "tools.web.search.maxResults": "Web 搜索 最大 Results",
  "tools.web.search.timeoutSeconds": "Web 搜索 超时（sec）",
  "tools.web.search.cacheTtlMinutes": "Web 搜索 缓存 TTL（min）",
  "tools.web.search.openaiCodex.enabled": "启用 原生 Codex Web 搜索",
  "tools.web.search.openaiCodex.mode": "Codex Web 搜索 模式",
  "tools.web.search.openaiCodex.allowedDomains": "Codex 允许 Domains",
  "tools.web.search.openaiCodex.contextSize": "Codex 搜索 上下文大小",
  "tools.web.search.openaiCodex.userLocation.country": "Codex User 国家",
  "tools.web.search.openaiCodex.userLocation.region": "Codex User 地区",
  "tools.web.search.openaiCodex.userLocation.city": "Codex User 城市",
  "tools.web.search.openaiCodex.userLocation.timezone": "Codex User 时区",
  "tools.web.search.brave.mode": "Brave 搜索 模式",
  "tools.web.fetch.enabled": "启用 Web 抓取 工具",
  "tools.web.fetch.maxChars": "Web 抓取 最大 字符",
  "tools.web.fetch.maxCharsCap": "Web 抓取 硬最大 字符",
  "tools.web.fetch.maxResponseBytes": "Web 抓取 最大 下载大小（bytes）",
  "tools.web.fetch.provider": "Web 抓取提供商",
  "tools.web.fetch.timeoutSeconds": "Web 抓取 超时（sec）",
  "tools.web.fetch.cacheTtlMinutes": "Web 抓取 缓存 TTL（min）",
  "tools.web.fetch.maxRedirects": "Web 抓取 最大 重定向",
  "tools.web.fetch.userAgent": "Web 抓取 用户代理",
  "tools.web.fetch.readability": "Web 抓取 可读性 Extraction",
  "gateway.controlUi.basePath": "控制界面基础路径",
  "gateway.controlUi.root": "控制界面资源根目录",
  "gateway.controlUi.allowedOrigins": "控制界面允许的来源",
  "gateway.controlUi.dangerouslyAllowHostHeaderOriginFallback":
    "危险地 允许 主机-请求头 来源 回退",
  "gateway.controlUi.allowInsecureAuth": "Insecure 控制界面 认证 Toggle",
  "gateway.controlUi.dangerouslyDisableDeviceAuth": "危险地 Disable 控制界面 Device 认证",
  "gateway.push": "网关 Push 传递",
  "gateway.push.apns": "网关 APNs 传递",
  "gateway.push.apns.relay": "网关 APNs Relay",
  "gateway.push.apns.relay.baseUrl": "网关 APNs Relay 基础 URL",
  "gateway.push.apns.relay.timeoutMs": "网关 APNs Relay 超时（ms）",
  "gateway.http.endpoints.chatCompletions.enabled": "打开AI Chat 完成s 端点",
  "gateway.http.endpoints.chatCompletions.maxBodyBytes": "打开AI Chat 完成s 最大 Body 字节",
  "gateway.http.endpoints.chatCompletions.maxImageParts": "打开AI Chat 完成s 最大 Image Parts",
  "gateway.http.endpoints.chatCompletions.maxTotalImageBytes":
    "打开AI Chat 完成s 最大 Total Image 字节",
  "gateway.http.endpoints.chatCompletions.images": "打开AI Chat 完成s Image 限制s",
  "gateway.http.endpoints.chatCompletions.images.allowUrl":
    "打开AI Chat 完成s 允许 Image URLs",
  "gateway.http.endpoints.chatCompletions.images.urlAllowlist":
    "打开AI Chat 完成s Image URL 允许列表",
  "gateway.http.endpoints.chatCompletions.images.allowedMimes":
    "打开AI Chat 完成s Image MIME 允许列表",
  "gateway.http.endpoints.chatCompletions.images.maxBytes":
    "打开AI Chat 完成s Image 最大 字节",
  "gateway.http.endpoints.chatCompletions.images.maxRedirects":
    "打开AI Chat 完成s Image 最大 重定向",
  "gateway.http.endpoints.chatCompletions.images.timeoutMs":
    "打开AI Chat 完成s Image 超时（ms）",
  "gateway.reload.mode": "配置重载 模式",
  "gateway.reload.debounceMs": "配置重载 Debounce（ms）",
  "gateway.reload.deferralTimeoutMs": "Restart Deferral 超时（ms）",
  "gateway.nodes.browser.mode": "网关 Node 浏览器 模式",
  "gateway.nodes.browser.node": "网关 Node 浏览器 Pin",
  "gateway.nodes.allowCommands": "网关 Node 允许列表（Extra 命令）",
  "gateway.nodes.denyCommands": "网关 Node 拒绝列表",
  "gateway.webchat.chatHistoryMaxChars": "WebChat History 最大 字符",
  nodeHost: "节点主机",
  "nodeHost.browserProxy": "Node 浏览器 代理",
  "nodeHost.browserProxy.enabled": "Node 浏览器 代理 已启用",
  "nodeHost.browserProxy.allowProfiles": "Node 浏览器 代理 允许 配置集",
  media: "媒体",
  "media.preserveFilenames": "Preserve Media 文件names",
  "media.ttlHours": "Media Retention TTL（hours）",
  audio: "音频",
  "audio.transcription": "Audio Transcription",
  "audio.transcription.command": "Audio Transcription 命令",
  "audio.transcription.timeoutSeconds": "Audio Transcription 超时（sec）",
  bindings: "绑定",
  "bindings[].type": "绑定 类型",
  "bindings[].agentId": "绑定 代理 ID",
  "bindings[].match": "绑定 Match 规则",
  "bindings[].match.channel": "绑定 通道",
  "bindings[].match.accountId": "绑定 账户 ID",
  "bindings[].match.peer": "绑定 Peer Match",
  "bindings[].match.peer.kind": "绑定 Peer Kind",
  "bindings[].match.peer.id": "绑定 Peer ID",
  "bindings[].match.guildId": "绑定 Guild ID",
  "bindings[].match.teamId": "绑定 Team ID",
  "bindings[].match.roles": "绑定 Roles",
  "bindings[].acp": "ACP 绑定 覆盖",
  "bindings[].acp.mode": "ACP 绑定 模式",
  "bindings[].acp.label": "ACP 绑定 Label",
  "bindings[].acp.cwd": "ACP 绑定 工作目录",
  "bindings[].acp.backend": "ACP 绑定 后端",
  broadcast: "Broadcast",
  "broadcast.strategy": "Broadcast Strategy",
  "broadcast.*": "Broadcast 目标地址 List",
  "skills.load.watch": "Watch 技能",
  "skills.load.watchDebounceMs": "技能 Watch Debounce（ms）",
  "agents.defaults.skills": "技能",
  "agents.defaults.workspace": "工作区",
  "agents.defaults.repoRoot": "Repo 根目录",
  "agents.defaults.contextInjection": "Context Injection",
  "agents.defaults.bootstrapMaxChars": "Bootstrap 最大 字符",
  "agents.defaults.bootstrapTotalMaxChars": "Bootstrap Total 最大 字符",
  "agents.defaults.bootstrapPromptTruncationWarning": "Bootstrap 提示词 Truncation 警告",
  "agents.defaults.envelopeTimezone": "Envelope 时区",
  "agents.defaults.envelopeTimestamp": "Envelope 时间戳",
  "agents.defaults.envelopeElapsed": "Envelope Elapsed",
  "agents.defaults.memorySearch": "记忆 搜索",
  "agents.defaults.memorySearch.enabled": "启用 记忆 搜索",
  "agents.defaults.memorySearch.sources": "记忆 搜索 Sources",
  "agents.defaults.memorySearch.extraPaths": "Extra 记忆 路径s",
  "agents.defaults.memorySearch.qmd": "记忆 搜索 QMD Collections",
  "agents.defaults.memorySearch.qmd.extraCollections": "QMD Extra Collections",
  "agents.defaults.memorySearch.qmd.extraCollections.path": "QMD Extra Collection 路径",
  "agents.defaults.memorySearch.qmd.extraCollections.name": "QMD Extra Collection Name",
  "agents.defaults.memorySearch.qmd.extraCollections.pattern": "QMD Extra Collection Pattern",
  "agents.defaults.memorySearch.multimodal": "记忆 搜索 Multimodal",
  "agents.defaults.memorySearch.multimodal.enabled": "启用 记忆 搜索 Multimodal",
  "agents.defaults.memorySearch.multimodal.modalities": "记忆 搜索 Multimodal Modalities",
  "agents.defaults.memorySearch.multimodal.maxFileBytes": "记忆 搜索 Multimodal 最大 文件 字节",
  "agents.defaults.memorySearch.experimental.sessionMemory":
    "记忆 搜索 会话 Index（实验性）",
  "agents.defaults.memorySearch.provider": "记忆 搜索 提供商",
  "agents.defaults.memorySearch.remote.baseUrl": "Remote Embedding 基础 URL",
  "agents.defaults.memorySearch.remote.apiKey": "Remote Embedding API 键",
  "agents.defaults.memorySearch.remote.headers": "Remote Embedding 请求头",
  "agents.defaults.memorySearch.remote.batch.enabled": "Remote Batch Embedding 已启用",
  "agents.defaults.memorySearch.remote.batch.wait": "Remote Batch Wait for 完成",
  "agents.defaults.memorySearch.remote.batch.concurrency": "Remote Batch 并发",
  "agents.defaults.memorySearch.remote.batch.pollIntervalMs": "Remote Batch Poll 间隔（ms）",
  "agents.defaults.memorySearch.remote.batch.timeoutMinutes": "Remote Batch 超时（min）",
  "agents.defaults.memorySearch.model": "记忆 搜索 模型",
  "agents.defaults.memorySearch.outputDimensionality": "记忆 搜索 Output Dimensionality",
  "agents.defaults.memorySearch.fallback": "记忆 搜索 回退",
  "agents.defaults.memorySearch.local.modelPath": "Local Embedding 模型 路径",
  "agents.defaults.memorySearch.store.path": "记忆 搜索 Index 路径",
  "agents.defaults.memorySearch.store.vector.enabled": "记忆 搜索 Vector Index",
  "agents.defaults.memorySearch.store.vector.extensionPath": "记忆 搜索 Vector Extension 路径",
  "agents.defaults.memorySearch.chunking.tokens": "记忆 Chunk 令牌s",
  "agents.defaults.memorySearch.chunking.overlap": "记忆 Chunk Overlap 令牌s",
  "agents.defaults.memorySearch.sync.onSessionStart": "Index on 会话 启动",
  "agents.defaults.memorySearch.sync.onSearch": "Index on 搜索（Lazy）",
  "agents.defaults.memorySearch.sync.watch": "Watch 记忆 文件",
  "agents.defaults.memorySearch.sync.watchDebounceMs": "记忆 Watch Debounce（ms）",
  "agents.defaults.memorySearch.sync.sessions.deltaBytes": "会话 Delta 字节",
  "agents.defaults.memorySearch.sync.sessions.deltaMessages": "会话 Delta 消息",
  "agents.defaults.memorySearch.sync.sessions.postCompactionForce":
    "Force Reindex After Compaction",
  "agents.defaults.memorySearch.query.maxResults": "记忆 搜索 最大 Results",
  "agents.defaults.memorySearch.query.minScore": "记忆 搜索 最小 Score",
  "agents.defaults.memorySearch.query.hybrid.enabled": "记忆 搜索 Hybrid",
  "agents.defaults.memorySearch.query.hybrid.vectorWeight": "记忆 搜索 Vector Weight",
  "agents.defaults.memorySearch.query.hybrid.textWeight": "记忆 搜索 Text Weight",
  "agents.defaults.memorySearch.query.hybrid.candidateMultiplier":
    "记忆 搜索 Hybrid Candidate Multiplier",
  "agents.defaults.memorySearch.query.hybrid.mmr.enabled": "记忆 搜索 MMR Re-ranking",
  "agents.defaults.memorySearch.query.hybrid.mmr.lambda": "记忆 搜索 MMR Lambda",
  "agents.defaults.memorySearch.query.hybrid.temporalDecay.enabled": "记忆 搜索 Temporal Decay",
  "agents.defaults.memorySearch.query.hybrid.temporalDecay.halfLifeDays":
    "记忆 搜索 Temporal Decay Half-life（Days）",
  "agents.defaults.memorySearch.cache.enabled": "记忆 搜索 Embedding Cache",
  "agents.defaults.memorySearch.cache.maxEntries": "记忆 搜索 Embedding Cache 最大 Entries",
  memory: "记忆",
  "memory.backend": "记忆 后端",
  "memory.citations": "记忆 Citations 模式",
  "memory.qmd.command": "QMD Binary",
  "memory.qmd.mcporter": "QMD MC端口er",
  "memory.qmd.mcporter.enabled": "QMD MC端口er 已启用",
  "memory.qmd.mcporter.serverName": "QMD MC端口er Server Name",
  "memory.qmd.mcporter.startDaemon": "QMD MC端口er 启动 Daemon",
  "memory.qmd.searchMode": "QMD 搜索 模式",
  "memory.qmd.searchTool": "QMD 搜索 工具 覆盖",
  "memory.qmd.includeDefaultMemory": "QMD 包含 默认 记忆",
  "memory.qmd.paths": "QMD Extra 路径s",
  "memory.qmd.paths.path": "QMD 路径",
  "memory.qmd.paths.pattern": "QMD 路径 Pattern",
  "memory.qmd.paths.name": "QMD 路径 Name",
  "memory.qmd.sessions.enabled": "QMD 会话 Indexing",
  "memory.qmd.sessions.exportDir": "QMD 会话 Export 目录",
  "memory.qmd.sessions.retentionDays": "QMD 会话 Retention（days）",
  "memory.qmd.update.interval": "QMD Update 间隔",
  "memory.qmd.update.debounceMs": "QMD Update Debounce（ms）",
  "memory.qmd.update.onBoot": "QMD Update on 启动up",
  "memory.qmd.update.waitForBootSync": "QMD Wait for Boot Sync",
  "memory.qmd.update.embedInterval": "QMD Embed 间隔",
  "memory.qmd.update.commandTimeoutMs": "QMD 命令 超时（ms）",
  "memory.qmd.update.updateTimeoutMs": "QMD Update 超时（ms）",
  "memory.qmd.update.embedTimeoutMs": "QMD Embed 超时（ms）",
  "memory.qmd.limits.maxResults": "QMD 最大 Results",
  "memory.qmd.limits.maxSnippetChars": "QMD 最大 Snippet 字符",
  "memory.qmd.limits.maxInjectedChars": "QMD 最大 Injected 字符",
  "memory.qmd.limits.timeoutMs": "QMD 搜索 超时（ms）",
  "memory.qmd.scope": "QMD Surface 范围",
  auth: "认证",
  "auth.profiles": "认证 配置集",
  "auth.order": "认证 配置 Order",
  "auth.cooldowns": "认证 Cooldowns",
  acp: "ACP",
  "acp.enabled": "ACP 已启用",
  "acp.dispatch.enabled": "ACP Dispatch 已启用",
  "acp.backend": "ACP 后端",
  "acp.defaultAgent": "ACP 默认 代理",
  "acp.allowedAgents": "ACP 允许 代理",
  "acp.maxConcurrentSessions": "ACP 最大 Concurrent 会话",
  "acp.stream": "ACP Stream",
  "acp.stream.coalesceIdleMs": "ACP Stream Coalesce Idle（ms）",
  "acp.stream.maxChunkChars": "ACP Stream 最大 Chunk 字符",
  "acp.stream.repeatSuppression": "ACP Stream 重复 抑制ion",
  "acp.stream.deliveryMode": "ACP Stream 传递 模式",
  "acp.stream.hiddenBoundarySeparator": "ACP Stream 隐藏边界分隔符",
  "acp.stream.maxOutputChars": "ACP Stream 最大 Output 字符",
  "acp.stream.maxSessionUpdateChars": "ACP Stream 最大 会话 Update 字符",
  "acp.stream.tagVisibility": "ACP Stream Tag 可见性",
  "acp.runtime.ttlMinutes": "ACP 运行时 TTL（minutes）",
  "acp.runtime.installCommand": "ACP 运行时 安装 命令",
  models: "模型",
  "models.mode": "模型 Catalog 模式",
  "models.providers": "模型 提供商",
  "models.providers.*.baseUrl": "模型 提供商 基础 URL",
  "models.providers.*.apiKey": "模型 提供商 API 键", // pragma: allowlist secret
  "models.providers.*.auth": "模型 提供商 认证 模式",
  "models.providers.*.api": "模型 提供商 API Adapter",
  "models.providers.*.injectNumCtxForOpenAICompat": "模型 提供商 Inject num_ctx（打开AI Compat）",
  "models.providers.*.headers": "模型 提供商 请求头",
  "models.providers.*.authHeader": "模型 提供商 认证orization 请求头",
  "models.providers.*.request": "模型 提供商 Request 覆盖",
  "models.providers.*.request.headers": "模型 提供商 Request 请求头",
  "models.providers.*.request.auth": "模型 提供商 Request 认证 覆盖",
  "models.providers.*.request.auth.mode": "模型 提供商 Request 认证 模式",
  "models.providers.*.request.auth.token": "模型 提供商 Request Bearer 令牌",
  "models.providers.*.request.auth.headerName": "模型 提供商 Request 认证 请求头 Name",
  "models.providers.*.request.auth.value": "模型 提供商 Request 认证 请求头 Value",
  "models.providers.*.request.auth.prefix": "模型 提供商 Request 认证 请求头 前缀",
  "models.providers.*.request.proxy": "模型 提供商 Request 代理",
  "models.providers.*.request.proxy.mode": "模型 提供商 Request 代理 模式",
  "models.providers.*.request.proxy.url": "模型 提供商 Request 代理 URL",
  "models.providers.*.request.proxy.tls": "模型 提供商 Request 代理 TLS",
  "models.providers.*.request.proxy.tls.ca": "模型 提供商 Request 代理 TLS CA",
  "models.providers.*.request.proxy.tls.cert": "模型 提供商 Request 代理 TLS 证书",
  "models.providers.*.request.proxy.tls.key": "模型 提供商 Request 代理 TLS 键",
  "models.providers.*.request.proxy.tls.passphrase": "模型 提供商 Request 代理 TLS Passphrase",
  "models.providers.*.request.proxy.tls.serverName": "模型 提供商 Request 代理 TLS Server Name",
  "models.providers.*.request.proxy.tls.insecureSkipVerify":
    "模型 提供商 Request 代理 TLS Skip Verify",
  "models.providers.*.request.tls": "模型 提供商 Request TLS",
  "models.providers.*.request.tls.ca": "模型 提供商 Request TLS CA",
  "models.providers.*.request.tls.cert": "模型 提供商 Request TLS 证书",
  "models.providers.*.request.tls.key": "模型 提供商 Request TLS 键",
  "models.providers.*.request.tls.passphrase": "模型 提供商 Request TLS Passphrase",
  "models.providers.*.request.tls.serverName": "模型 提供商 Request TLS Server Name",
  "models.providers.*.request.tls.insecureSkipVerify": "模型 提供商 Request TLS Skip Verify",
  "models.providers.*.models": "模型 提供商 模型 List",
  "auth.cooldowns.billingBackoffHours": "Billing Backoff（hours）",
  "auth.cooldowns.billingBackoffHoursByProvider": "Billing Backoff 覆盖",
  "auth.cooldowns.billingMaxHours": "Billing Backoff Cap（hours）",
  "auth.cooldowns.authPermanentBackoffMinutes": "认证-Permanent Backoff（minutes）",
  "auth.cooldowns.authPermanentMaxMinutes": "认证-Permanent Backoff Cap（minutes）",
  "auth.cooldowns.failureWindowHours": "Failover Window（hours）",
  "auth.cooldowns.overloadedProfileRotations": "Overloaded 配置 Rotations",
  "auth.cooldowns.overloadedBackoffMs": "Overloaded Backoff（ms）",
  "auth.cooldowns.rateLimitedProfileRotations": "Rate-限制ed 配置 Rotations",
  "agents.defaults.models": "模型",
  "agents.defaults.model.primary": "Primary 模型",
  "agents.defaults.model.fallbacks": "模型 回退s",
  "agents.defaults.imageModel.primary": "Image 模型",
  "agents.defaults.imageModel.fallbacks": "Image 模型 回退s",
  "agents.defaults.imageGenerationModel.primary": "Image Generation 模型",
  "agents.defaults.imageGenerationModel.fallbacks": "Image Generation 模型 回退s",
  "agents.defaults.videoGenerationModel.primary": "Video Generation 模型",
  "agents.defaults.videoGenerationModel.fallbacks": "Video Generation 模型 回退s",
  "agents.defaults.musicGenerationModel.primary": "Music Generation 模型",
  "agents.defaults.musicGenerationModel.fallbacks": "Music Generation 模型 回退s",
  "agents.defaults.mediaGenerationAutoProviderFallback": "Media Generation 自动 提供商 回退",
  "agents.defaults.pdfModel.primary": "PDF 模型",
  "agents.defaults.pdfModel.fallbacks": "PDF 模型 回退s",
  "agents.defaults.pdfMaxBytesMb": "PDF 最大 Size（MB）",
  "agents.defaults.pdfMaxPages": "PDF 最大 Pages",
  "agents.defaults.imageMaxDimensionPx": "Image 最大 Dimension（px）",
  "agents.defaults.humanDelay.mode": "Human Delay 模式",
  "agents.defaults.humanDelay.minMs": "Human Delay 最小（ms）",
  "agents.defaults.humanDelay.maxMs": "Human Delay 最大（ms）",
  "agents.defaults.cliBackends": "CLI 后端",
  "agents.defaults.compaction": "Compaction",
  "agents.defaults.compaction.mode": "Compaction 模式",
  "agents.defaults.compaction.provider": "Compaction 提供商",
  "agents.defaults.compaction.reserveTokens": "Compaction Reserve 令牌s",
  "agents.defaults.compaction.keepRecentTokens": "Compaction Keep 最近 令牌s",
  "agents.defaults.compaction.reserveTokensFloor": "Compaction Reserve 令牌 Floor",
  "agents.defaults.compaction.maxHistoryShare": "Compaction 最大 History Share",
  "agents.defaults.compaction.identifierPolicy": "Compaction Identifier 策略",
  "agents.defaults.compaction.identifierInstructions": "Compaction Identifier Instructions",
  "agents.defaults.compaction.recentTurnsPreserve": "Compaction Preserve 最近 Turns",
  "agents.defaults.compaction.qualityGuard": "Compaction Quality Guard",
  "agents.defaults.compaction.qualityGuard.enabled": "Compaction Quality Guard 已启用",
  "agents.defaults.compaction.qualityGuard.maxRetries": "Compaction Quality Guard 最大 Retries",
  "agents.defaults.compaction.postIndexSync": "Compaction Post-Index Sync",
  "agents.defaults.compaction.postCompactionSections": "Post-Compaction Context Sections",
  "agents.defaults.compaction.timeoutSeconds": "Compaction 超时（秒）",
  "agents.defaults.compaction.model": "Compaction 模型 覆盖",
  "agents.defaults.compaction.truncateAfterCompaction": "Truncate After Compaction",
  "agents.defaults.compaction.notifyUser": "Compaction 通知 User",
  "agents.defaults.compaction.memoryFlush": "Compaction 记忆 刷新",
  "agents.defaults.compaction.memoryFlush.enabled": "Compaction 记忆 刷新 已启用",
  "agents.defaults.compaction.memoryFlush.softThresholdTokens":
    "Compaction 记忆 刷新 Soft 阈值",
  "agents.defaults.compaction.memoryFlush.forceFlushTranscriptBytes":
    "Compaction 记忆 刷新 Transcript Size 阈值",
  "agents.defaults.compaction.memoryFlush.prompt": "Compaction 记忆 刷新 提示词",
  "agents.defaults.compaction.memoryFlush.systemPrompt": "Compaction 记忆 刷新 系统 提示词",
  "agents.defaults.embeddedPi": "Embedded Pi",
  "agents.defaults.embeddedPi.projectSettingsPolicy": "Embedded Pi Project Settings 策略",
  "agents.defaults.heartbeat.includeSystemPromptSection": "心跳 包含 系统 提示词 Section",
  "agents.list.*.heartbeat.includeSystemPromptSection": "心跳 包含 系统 提示词 Section",
  "agents.defaults.heartbeat.directPolicy": "心跳 目录ect 策略",
  "agents.list.*.heartbeat.directPolicy": "心跳 目录ect 策略",
  "agents.defaults.heartbeat.suppressToolErrorWarnings": "心跳 抑制 工具 错误 警告",
  "agents.defaults.sandbox.browser.network": "沙箱 浏览器 Network",
  "agents.defaults.sandbox.browser.cdpSourceScope": "沙箱浏览器 CDP 来源范围",
  "agents.defaults.sandbox.docker.dangerouslyAllowContainerNamespaceJoin":
    "沙箱 Docker 允许 Container Namespace Join",
  commands: "命令",
  "commands.native": "原生 命令",
  "commands.nativeSkills": "原生 技能 命令",
  "commands.text": "Text 命令",
  "commands.bash": "允许 Bash Chat 命令",
  "commands.bashForegroundMs": "Bash Foreground Window（ms）",
  "commands.config": "允许 /config",
  "commands.mcp": "允许 /mcp",
  "commands.plugins": "允许 /plugins",
  "commands.debug": "允许 /debug",
  "commands.restart": "允许 Restart",
  "commands.useAccessGroups": "Use 访问 Groups",
  "commands.ownerAllowFrom": "命令 Owners",
  "commands.ownerDisplay": "Owner ID Display",
  "commands.ownerDisplaySecret": "Owner ID Hash Secret", // pragma: allowlist secret
  "commands.allowFrom": "命令 提权 访问 规则",
  mcp: "MCP",
  "mcp.servers": "MCP Servers",
  ui: "界面",
  "ui.seamColor": "强调色",
  "ui.assistant": "Assistant Appearance",
  "ui.assistant.name": "Assistant Name",
  "ui.assistant.avatar": "Assistant 头像",
  "browser.evaluateEnabled": "浏览器 Evaluate 已启用",
  "browser.snapshotDefaults": "浏览器 Snapshot 默认值",
  "browser.snapshotDefaults.mode": "浏览器 Snapshot 模式",
  "browser.ssrfPolicy": "浏览器 SSRF 策略",
  "browser.ssrfPolicy.dangerouslyAllowPrivateNetwork": "浏览器 危险地 允许 Private Network",
  "browser.ssrfPolicy.allowedHostnames": "浏览器 允许 主机names",
  "browser.ssrfPolicy.hostnameAllowlist": "浏览器 主机name 允许列表",
  "browser.remoteCdpTimeoutMs": "Remote CDP 超时（ms）",
  "browser.remoteCdpHandshakeTimeoutMs": "Remote CDP Handshake 超时（ms）",
  session: "会话",
  "session.scope": "会话 范围",
  "session.dmScope": "DM 会话 范围",
  "session.identityLinks": "会话 身份 Links",
  "session.resetTriggers": "会话 Reset Triggers",
  "session.idleMinutes": "会话 Idle 分钟",
  "session.reset": "会话 Reset 策略",
  "session.reset.mode": "会话 Reset 模式",
  "session.reset.atHour": "会话 Daily Reset 小时",
  "session.reset.idleMinutes": "会话 Reset Idle 分钟",
  "session.resetByType": "会话重置来源类型",
  "session.resetByType.direct": "会话重置来源类型 Direct",
  "session.resetByType.dm": "会话重置来源类型 DM",
  "session.resetByType.group": "会话重置来源类型 Group",
  "session.resetByType.thread": "会话重置来源类型 Thread",
  "session.resetByChannel": "会话 Reset by 通道",
  "session.store": "会话 Store 路径",
  "session.typingIntervalSeconds": "会话 Typing 间隔（seconds）",
  "session.typingMode": "会话 Typing 模式",
  "session.parentForkMaxTokens": "会话 Parent Fork 最大 令牌s",
  "session.mainKey": "会话 Main 键",
  "session.sendPolicy": "会话 Send 策略",
  "session.sendPolicy.default": "会话 Send 策略 默认 Action",
  "session.sendPolicy.rules": "会话 Send 策略 规则",
  "session.sendPolicy.rules[].action": "会话 Send 规则 Action",
  "session.sendPolicy.rules[].match": "会话 Send 规则 Match",
  "session.sendPolicy.rules[].match.channel": "会话 Send 规则 通道",
  "session.sendPolicy.rules[].match.chatType": "会话发送规则聊天类型",
  "session.sendPolicy.rules[].match.keyPrefix": "会话 Send 规则 键 前缀",
  "session.sendPolicy.rules[].match.rawKeyPrefix": "会话 Send 规则 Raw 键 前缀",
  "session.agentToAgent": "会话 代理到代理",
  "session.agentToAgent.maxPingPongTurns": "代理到代理 乒乓 Turns",
  "session.threadBindings": "会话 Thread 绑定",
  "session.threadBindings.enabled": "Thread 绑定 已启用",
  "session.threadBindings.idleHours": "Thread 绑定 Idle 超时（hours）",
  "session.threadBindings.maxAgeHours": "Thread 绑定 最大 Age（hours）",
  "session.maintenance": "会话 Maintenance",
  "session.maintenance.mode": "会话 Maintenance 模式",
  "session.maintenance.pruneAfter": "会话 Prune After",
  "session.maintenance.pruneDays": "会话 Prune Days（Deprecated）",
  "session.maintenance.maxEntries": "会话 最大 Entries",
  "session.maintenance.rotateBytes": "会话 Rotate Size",
  "session.maintenance.resetArchiveRetention": "会话 Reset Archive Retention",
  "session.maintenance.maxDiskBytes": "会话 最大 Disk Budget",
  "session.maintenance.highWaterBytes": "会话 Disk High-water 目标",
  cron: "定时任务",
  "cron.enabled": "Cron 已启用",
  "cron.store": "Cron Store 路径",
  "cron.maxConcurrentRuns": "Cron 最大 Concurrent Runs",
  "cron.retry": "Cron Retry 策略",
  "cron.retry.maxAttempts": "Cron Retry 最大 Attempts",
  "cron.retry.backoffMs": "Cron Retry Backoff（ms）",
  "cron.retry.retryOn": "Cron Retry 错误 类型s",
  "cron.webhook": "Cron Legacy Webhook（Deprecated）",
  "cron.webhookToken": "Cron Webhook Bearer 令牌",
  "cron.sessionRetention": "Cron 会话 Retention",
  "cron.runLog": "Cron Run 日志 Pruning",
  "cron.runLog.maxBytes": "Cron Run 日志 最大 字节",
  "cron.runLog.keepLines": "Cron Run 日志 Keep Lines",
  hooks: "钩子",
  "hooks.enabled": "钩子 已启用",
  "hooks.path": "钩子 端点 路径",
  "hooks.token": "钩子 认证 令牌",
  "hooks.defaultSessionKey": "钩子 默认 会话 键",
  "hooks.allowRequestSessionKey": "钩子 允许 Request 会话 键",
  "hooks.allowedSessionKeyPrefixes": "钩子 允许 会话 键 前缀es",
  "hooks.allowedAgentIds": "钩子 允许 代理 IDs",
  "hooks.maxBodyBytes": "钩子 最大 Body 字节",
  "hooks.presets": "钩子 Presets",
  "hooks.transformsDir": "钩子 Transforms 目录",
  "hooks.mappings": "钩子 Mappings",
  "hooks.mappings[].id": "钩子 Mapping ID",
  "hooks.mappings[].match": "钩子 Mapping Match",
  "hooks.mappings[].match.path": "钩子 Mapping Match 路径",
  "hooks.mappings[].match.source": "钩子 Mapping Match Source",
  "hooks.mappings[].action": "钩子 Mapping Action",
  "hooks.mappings[].wakeMode": "钩子 Mapping Wake 模式",
  "hooks.mappings[].name": "钩子 Mapping Name",
  "hooks.mappings[].agentId": "钩子 Mapping 代理 ID",
  "hooks.mappings[].sessionKey": "钩子 Mapping 会话 键",
  "hooks.mappings[].messageTemplate": "钩子 Mapping 消息 Template",
  "hooks.mappings[].textTemplate": "钩子 Mapping Text Template",
  "hooks.mappings[].deliver": "钩子 Mapping Deliver Reply",
  "hooks.mappings[].allowUnsafeExternalContent": "钩子 Mapping 允许 Unsafe External Content",
  "hooks.mappings[].channel": "钩子 Mapping 传递 通道",
  "hooks.mappings[].to": "钩子 Mapping 传递 目标地址",
  "hooks.mappings[].model": "钩子 Mapping 模型 覆盖",
  "hooks.mappings[].thinking": "钩子 Mapping 思考 覆盖",
  "hooks.mappings[].timeoutSeconds": "钩子 Mapping 超时（sec）",
  "hooks.mappings[].transform": "钩子 Mapping Transform",
  "hooks.mappings[].transform.module": "钩子 Transform Module",
  "hooks.mappings[].transform.export": "钩子 Transform Export",
  "hooks.gmail": "Gmail 钩子",
  "hooks.gmail.account": "Gmail 钩子 Account",
  "hooks.gmail.label": "Gmail 钩子 Label",
  "hooks.gmail.topic": "Gmail 钩子 Pub/Sub Topic",
  "hooks.gmail.subscription": "Gmail 钩子 Subscription",
  "hooks.gmail.pushToken": "Gmail 钩子 Push 令牌",
  "hooks.gmail.hookUrl": "Gmail 钩子 Callback URL",
  "hooks.gmail.includeBody": "Gmail 钩子 包含 Body",
  "hooks.gmail.maxBytes": "Gmail 钩子 最大 Body 字节",
  "hooks.gmail.renewEveryMinutes": "Gmail 钩子 Renew 间隔（min）",
  "hooks.gmail.allowUnsafeExternalContent": "Gmail 钩子 允许 Unsafe External Content",
  "hooks.gmail.serve": "Gmail 钩子 Local Server",
  "hooks.gmail.serve.bind": "Gmail 钩子 Server Bind Address",
  "hooks.gmail.serve.port": "Gmail 钩子 Server 端口",
  "hooks.gmail.serve.path": "Gmail 钩子 Server 路径",
  "hooks.gmail.tailscale": "Gmail 钩子 Tailscale",
  "hooks.gmail.tailscale.mode": "Gmail 钩子 Tailscale 模式",
  "hooks.gmail.tailscale.path": "Gmail 钩子 Tailscale 路径",
  "hooks.gmail.tailscale.target": "Gmail 钩子 Tailscale 目标",
  "hooks.gmail.model": "Gmail 钩子 模型 覆盖",
  "hooks.gmail.thinking": "Gmail 钩子 思考 覆盖",
  "hooks.internal": "Internal 钩子",
  "hooks.internal.enabled": "Internal 钩子 已启用",
  "hooks.internal.entries": "Internal 钩子 Entries",
  "hooks.internal.load": "Internal 钩子 Loader",
  "hooks.internal.load.extraDirs": "Internal 钩子 Extra 目录ectories",
  "hooks.internal.installs": "Internal 钩子 安装 Records",
  web: "Web 通道",
  "web.enabled": "Web 通道 已启用",
  "web.heartbeatSeconds": "Web 通道 心跳 间隔（sec）",
  "web.reconnect": "Web 通道 Reconnect 策略",
  "web.reconnect.initialMs": "Web Reconnect Initial Delay（ms）",
  "web.reconnect.maxMs": "Web Reconnect 最大 Delay（ms）",
  "web.reconnect.factor": "Web Reconnect Backoff Factor",
  "web.reconnect.jitter": "Web Reconnect 抖动",
  "web.reconnect.maxAttempts": "Web Reconnect 最大 Attempts",
  discovery: "发现",
  "discovery.wideArea": "Wide-area Discovery",
  "discovery.wideArea.enabled": "Wide-area Discovery 已启用",
  "discovery.wideArea.domain": "Wide-area Discovery Domain",
  "discovery.mdns": "mDNS Discovery",
  canvasHost: "Canvas 主机",
  "canvasHost.enabled": "Canvas 主机 已启用",
  "canvasHost.root": "Canvas 主机 根目录 目录",
  "canvasHost.port": "Canvas 主机 端口",
  "canvasHost.liveReload": "Canvas 主机 Live Reload",
  talk: "语音",
  "talk.interruptOnSpeech": "Talk Interrupt on Speech",
  "talk.silenceTimeoutMs": "Talk Silence 超时（ms）",
  messages: "消息",
  "messages.messagePrefix": "Inbound 消息 前缀",
  "messages.responsePrefix": "Outbound 响应 前缀",
  "messages.groupChat": "Group Chat 规则",
  "messages.groupChat.mentionPatterns": "Group Mention Patterns",
  "messages.groupChat.historyLimit": "Group History 限制",
  "messages.queue": "Inbound Queue",
  "messages.queue.mode": "Queue 模式",
  "messages.queue.byChannel": "Queue 模式 by 通道",
  "messages.queue.debounceMs": "Queue Debounce（ms）",
  "messages.queue.debounceMsByChannel": "Queue Debounce by 通道（ms）",
  "messages.queue.cap": "Queue Capacity",
  "messages.queue.drop": "Queue Drop Strategy",
  "messages.inbound": "Inbound Debounce",
  "messages.suppressToolErrors": "抑制 工具 错误 警告",
  "messages.ackReaction": "Ack Reaction Emoji",
  "messages.ackReactionScope": "Ack Reaction 范围",
  "messages.removeAckAfterReply": "Remove Ack Reaction After Reply",
  "messages.statusReactions": "Status Reactions",
  "messages.statusReactions.enabled": "启用 Status Reactions",
  "messages.statusReactions.emojis": "Status Reaction Emojis",
  "messages.statusReactions.timing": "Status Reaction Timing",
  "messages.inbound.debounceMs": "Inbound 消息 Debounce（ms）",
  "messages.inbound.byChannel": "Inbound Debounce by 通道（ms）",
  "messages.tts": "消息 Text-to-Speech",
  "messages.tts.providers": "TTS 提供商 Settings",
  "messages.tts.providers.*": "TTS 提供商 Config",
  "messages.tts.providers.*.apiKey": "TTS 提供商 API 键", // pragma: allowlist secret
  "talk.provider": "Talk Active 提供商",
  "talk.providers": "Talk 提供商 Settings",
  "talk.providers.*": "Talk 提供商 Config",
  "talk.providers.*.apiKey": "Talk 提供商 API 键", // pragma: allowlist secret
  channels: "通道",
  "channels.defaults": "通道 默认值",
  "channels.defaults.groupPolicy": "默认 Group 策略",
  "channels.defaults.contextVisibility": "默认 Context 可见性",
  "channels.defaults.heartbeat": "默认 心跳 可见性",
  "channels.defaults.heartbeat.showOk": "心跳 Show OK",
  "channels.defaults.heartbeat.showAlerts": "心跳 Show Alerts",
  "channels.defaults.heartbeat.useIndicator": "心跳 Use Indicator",
  "channels.mattermost": "Mattermost",
  "channels.modelByChannel": "通道 模型 覆盖",
  "channels.matrix.allowBots": "Matrix 允许 Bot 消息",
  "channels.mattermost.botToken": "Mattermost Bot 令牌",
  "channels.mattermost.baseUrl": "Mattermost 基础 URL",
  "channels.mattermost.configWrites": "Mattermost Config Writes",
  "channels.mattermost.chatmode": "Mattermost Chat 模式",
  "channels.mattermost.oncharPrefixes": "Mattermost Onchar 前缀es",
  "channels.mattermost.requireMention": "Mattermost Require Mention",
  "agents.list[].skills": "代理 技能 过滤器",
  "agents.list[].identity.avatar": "代理 头像",
  "agents.list[].heartbeat.suppressToolErrorWarnings":
    "代理 心跳 抑制 工具 错误 警告",
  "agents.list[].sandbox.browser.network": "代理 沙箱 浏览器 Network",
  "agents.list[].sandbox.browser.cdpSourceScope": "代理沙箱浏览器 CDP 来源范围",
  "agents.list[].sandbox.docker.dangerouslyAllowContainerNamespaceJoin":
    "代理 沙箱 Docker 允许 Container Namespace Join",
  "discovery.mdns.mode": "mDNS Discovery 模式",
  plugins: "插件",
  "plugins.enabled": "启用 插件",
  "plugins.allow": "插件 允许列表",
  "plugins.deny": "插件 拒绝列表",
  "plugins.load": "插件 Loader",
  "plugins.load.paths": "插件 Load 路径s",
  "plugins.slots": "插件 Slots",
  "plugins.slots.memory": "记忆 插件",
  "plugins.slots.contextEngine": "Context Engine 插件",
  "plugins.entries": "插件 Entries",
  "plugins.entries.*.enabled": "插件 已启用",
  "plugins.entries.*.hooks": "插件 钩子 策略",
  "plugins.entries.*.hooks.allowPromptInjection": "允许 提示词 Injection 钩子",
  "plugins.entries.*.subagent": "插件 Subagent 策略",
  "plugins.entries.*.subagent.allowModelOverride": "允许 插件 Subagent 模型 覆盖",
  "plugins.entries.*.subagent.allowedModels": "插件子代理允许模型",
  "plugins.entries.*.apiKey": "插件 API 键", // pragma: allowlist secret
  "plugins.entries.*.env": "插件 环境 变量",
  "plugins.entries.*.config": "插件 Config",
  "plugins.installs": "插件 安装 Records",
  "plugins.installs.*.source": "插件 安装 Source",
  "plugins.installs.*.spec": "插件 安装 Spec",
  "plugins.installs.*.sourcePath": "插件 安装 Source 路径",
  "plugins.installs.*.installPath": "插件 安装 路径",
  "plugins.installs.*.version": "插件 安装 版本",
  "plugins.installs.*.resolvedName": "插件 Resolved Package Name",
  "plugins.installs.*.resolvedVersion": "插件 Resolved Package 版本",
  "plugins.installs.*.resolvedSpec": "插件 Resolved Package Spec",
  "plugins.installs.*.integrity": "插件 Resolved Integrity",
  "plugins.installs.*.shasum": "插件 Resolved Shasum",
  "plugins.installs.*.resolvedAt": "插件 Resolution Time",
  "plugins.installs.*.installedAt": "插件 安装 Time",
  "plugins.installs.*.marketplaceName": "插件 Marketplace Name",
  "plugins.installs.*.marketplaceSource": "插件 Marketplace Source",
  "plugins.installs.*.marketplacePlugin": "插件 Marketplace 插件",
};
